#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v20
# autospec commit: f35655a
#
# Source0 file verified with key 0x3353C9CEF108B584 (mdroth@utexas.edu)
#
Name     : qemu-guest-additions
Version  : 9.1.1
Release  : 144
URL      : https://download.qemu.org/qemu-9.1.1.tar.xz
Source0  : https://download.qemu.org/qemu-9.1.1.tar.xz
Source1  : qemu-guest-agent.service
Source2  : https://download.qemu.org/qemu-9.1.1.tar.xz.sig
Source3  : 3353C9CEF108B584.pkey
Summary  : OPAL firmware
Group    : Development/Tools
License  : Apache-2.0 Artistic-1.0 Artistic-1.0-Perl BSD-2-Clause BSD-2-Clause-Patent BSD-3-Clause CC0-1.0 GPL-1.0 GPL-2.0 GPL-3.0 HPND LGPL-2.1 LGPL-3.0 MIT
Requires: qemu-guest-additions-autostart = %{version}-%{release}
Requires: qemu-guest-additions-bin = %{version}-%{release}
Requires: qemu-guest-additions-license = %{version}-%{release}
Requires: qemu-guest-additions-man = %{version}-%{release}
Requires: qemu-guest-additions-services = %{version}-%{release}
BuildRequires : SDL2_image-dev
BuildRequires : attr-dev
BuildRequires : automake-dev
BuildRequires : bison
BuildRequires : buildreq-configure
BuildRequires : dtc-dev
BuildRequires : flex
BuildRequires : fuse-dev
BuildRequires : glib-dev
BuildRequires : gnupg
BuildRequires : gtk3-dev
BuildRequires : libaio-dev
BuildRequires : libcap-dev
BuildRequires : libcap-ng-dev
BuildRequires : libgcrypt-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libseccomp-dev
BuildRequires : libslirp-dev
BuildRequires : libssh-dev
BuildRequires : libssh2-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : liburing-dev
BuildRequires : m4
BuildRequires : nfs-utils-dev
BuildRequires : ninja
BuildRequires : numactl-dev
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(capstone)
BuildRequires : pkgconfig(fuse3)
BuildRequires : pkgconfig(gbm)
BuildRequires : pkgconfig(glusterfs-api)
BuildRequires : pkgconfig(gmp)
BuildRequires : pkgconfig(gnutls)
BuildRequires : pkgconfig(gvnc-1.0)
BuildRequires : pkgconfig(jack)
BuildRequires : pkgconfig(libbpf)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libdaxctl)
BuildRequires : pkgconfig(libdw)
BuildRequires : pkgconfig(libiscsi)
BuildRequires : pkgconfig(libkeyutils)
BuildRequires : pkgconfig(libpipewire-0.3)
BuildRequires : pkgconfig(libpmem)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libzstd)
BuildRequires : pkgconfig(ncursesw)
BuildRequires : pkgconfig(nettle)
BuildRequires : pkgconfig(qpl)
BuildRequires : pkgconfig(sysprof-capture-4)
BuildRequires : pkgconfig(virglrenderer)
BuildRequires : pkgconfig(vte-2.91)
BuildRequires : pypi(sphinx_rtd_theme)
BuildRequires : pypi-sphinx
BuildRequires : pypi-sphinx_rtd_theme
BuildRequires : qpl-dev
BuildRequires : snappy-dev
BuildRequires : spice
BuildRequires : spice-dev
BuildRequires : spice-protocol
BuildRequires : usbredir-dev
BuildRequires : util-linux-dev
BuildRequires : vte-dev
BuildRequires : zlib-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: 0001-Allow-unknown-options-in-configure-script.patch

%description
This package provides a daemon to load and run the OpenPower firmware's
Processor Recovery Diagnostics binary. This is responsible for run time
maintenance of OpenPower Systems hardware.

%package autostart
Summary: autostart components for the qemu-guest-additions package.
Group: Default

%description autostart
autostart components for the qemu-guest-additions package.


%package bin
Summary: bin components for the qemu-guest-additions package.
Group: Binaries
Requires: qemu-guest-additions-license = %{version}-%{release}
Requires: qemu-guest-additions-services = %{version}-%{release}

%description bin
bin components for the qemu-guest-additions package.


%package license
Summary: license components for the qemu-guest-additions package.
Group: Default

%description license
license components for the qemu-guest-additions package.


%package man
Summary: man components for the qemu-guest-additions package.
Group: Default

%description man
man components for the qemu-guest-additions package.


%package services
Summary: services components for the qemu-guest-additions package.
Group: Systemd services
Requires: systemd

%description services
services components for the qemu-guest-additions package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE3}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE2} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) 3353C9CEF108B584' gpg.status
%setup -q -n qemu-9.1.1
cd %{_builddir}/qemu-9.1.1
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1729783982
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static --disable-sdl \
--enable-vnc \
--enable-gtk \
--enable-kvm \
--disable-strip \
--target-list='i386-softmmu x86_64-softmmu i386-linux-user x86_64-linux-user' \
--enable-spice \
--disable-rbd \
--extra-cflags="-O3" \
--enable-attr \
--enable-cap-ng \
--enable-virtfs \
--enable-vhost-net \
--enable-usb-redir \
--python=/usr/bin/python \
--enable-seccomp \
--enable-linux-aio
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1729783982
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qemu-guest-additions
cp %{_builddir}/qemu-%{version}/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/2b9d60c2972b476384af9900276837ac81954e80 || :
cp %{_builddir}/qemu-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/qemu-guest-additions/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
cp %{_builddir}/qemu-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/c690b05ff6431c277b59784e95169e0e0528a983 || :
cp %{_builddir}/qemu-%{version}/roms/QemuMacDrivers/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/2b9d60c2972b476384af9900276837ac81954e80 || :
cp %{_builddir}/qemu-%{version}/roms/SLOF/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/e1f0ad62e4850a19b1f56b821f37fccbf84ec191 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/.pytool/Plugin/LicenseCheck/LicenseCheck_plug_in.yaml %{buildroot}/usr/share/package-licenses/qemu-guest-additions/f1a6a8f321d20cb5fbec859a848bff49ad31de69 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/ArmPkg/Library/ArmSoftFloatLib/berkeley-softfloat-3/COPYING.txt %{buildroot}/usr/share/package-licenses/qemu-guest-additions/c4cd5ba6f665cf9ecb44e0620c2c76140566cfc6 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/BaseTools/Source/C/BrotliCompress/brotli/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/c045813a6c514f2d30d60a07c6aaf3603850e608 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/CryptoPkg/Library/OpensslLib/openssl/LICENSE.txt %{buildroot}/usr/share/package-licenses/qemu-guest-additions/c5c8a68f4b80929b3e66f054f37bb9e16078847f || :
cp %{_builddir}/qemu-%{version}/roms/edk2/CryptoPkg/Library/OpensslLib/openssl/external/perl/Text-Template-1.56/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/f12894289cb0f379f24b8d63e2e761dbcba1b216 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/License-History.txt %{buildroot}/usr/share/package-licenses/qemu-guest-additions/1b5c06f43bf6e2039065b681398f6b99a4d552f8 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/License.txt %{buildroot}/usr/share/package-licenses/qemu-guest-additions/7fc5c71d1c403b07043376504d62f2ac73a75313 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/MdeModulePkg/Library/BrotliCustomDecompressLib/brotli/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/c045813a6c514f2d30d60a07c6aaf3603850e608 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/OvmfPkg/Bhyve/License.txt %{buildroot}/usr/share/package-licenses/qemu-guest-additions/6b5c7cbcd561ea8f6bba9dd24393f995c1a006e9 || :
cp %{_builddir}/qemu-%{version}/roms/edk2/OvmfPkg/License.txt %{buildroot}/usr/share/package-licenses/qemu-guest-additions/c9c057d4dc70e7a834d80b762663ca01a852ed13 || :
cp %{_builddir}/qemu-%{version}/roms/ipxe/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/cedc99c80ddc135681756e652d55c72d89ebdfe7 || :
cp %{_builddir}/qemu-%{version}/roms/ipxe/COPYING.GPLv2 %{buildroot}/usr/share/package-licenses/qemu-guest-additions/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/qemu-%{version}/roms/ipxe/src/include/ipxe/efi/LICENCE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/ca46b2cea92edc93654b11c06c0073ec1a2e50e8 || :
cp %{_builddir}/qemu-%{version}/roms/openbios/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/8b35225cbdbd6858fb081817cc9dbfe4bef26f5b || :
cp %{_builddir}/qemu-%{version}/roms/openbios/Documentation/kernel/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/e9b568889ca9075b505c509f7a877a723cc9a4b0 || :
cp %{_builddir}/qemu-%{version}/roms/openbios/utils/devbios/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/7475b0da13789cd598fe0703f5337d37dd8b0b95 || :
cp %{_builddir}/qemu-%{version}/roms/opensbi/COPYING.BSD %{buildroot}/usr/share/package-licenses/qemu-guest-additions/0a0d7ae8e993794ae9c9ac5219c3d2bbf289471f || :
cp %{_builddir}/qemu-%{version}/roms/opensbi/scripts/Kconfiglib/LICENSE.txt %{buildroot}/usr/share/package-licenses/qemu-guest-additions/864f15fbb4dcd073bbe20eb3c0b839a45b8902ab || :
cp %{_builddir}/qemu-%{version}/roms/qboot/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/30a6e0a424471d8ac874b5616dd5a18c45fd6046 || :
cp %{_builddir}/qemu-%{version}/roms/qemu-palcode/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/2b9d60c2972b476384af9900276837ac81954e80 || :
cp %{_builddir}/qemu-%{version}/roms/seabios-hppa/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/qemu-%{version}/roms/seabios-hppa/COPYING.LESSER %{buildroot}/usr/share/package-licenses/qemu-guest-additions/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9 || :
cp %{_builddir}/qemu-%{version}/roms/seabios/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
cp %{_builddir}/qemu-%{version}/roms/seabios/COPYING.LESSER %{buildroot}/usr/share/package-licenses/qemu-guest-additions/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/LICENCE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/ccan/array_size/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/ccan/build_assert/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/ccan/check_type/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/ccan/container_of/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/ccan/endian/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/ccan/heap/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/ccan/list/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/ccan/short_types/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/ccan/str/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3 || :
cp %{_builddir}/qemu-%{version}/roms/skiboot/libstb/crypto/mbedtls/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/4d6c5af1a9cc4eaab3b93353fc166d8e29c150c6 || :
cp %{_builddir}/qemu-%{version}/roms/u-boot-sam460ex/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/11bb99995c221415712bb5a6d6c0898f02936feb || :
cp %{_builddir}/qemu-%{version}/roms/u-boot-sam460ex/board/ACube/bios_emulator/scitech/src/x86emu/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/3f226d574cd9547c3e4d934bb1ac4be3601a9782 || :
cp %{_builddir}/qemu-%{version}/roms/u-boot-sam460ex/fs/jffs2/LICENCE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/2f02ed32418afe8cc25f30f269c63085bafe44f7 || :
cp %{_builddir}/qemu-%{version}/roms/u-boot/fs/jffs2/LICENCE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/2f02ed32418afe8cc25f30f269c63085bafe44f7 || :
cp %{_builddir}/qemu-%{version}/roms/vbootrom/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/qemu-%{version}/subprojects/berkeley-softfloat-3/COPYING.txt %{buildroot}/usr/share/package-licenses/qemu-guest-additions/c4cd5ba6f665cf9ecb44e0620c2c76140566cfc6 || :
cp %{_builddir}/qemu-%{version}/subprojects/berkeley-testfloat-3/COPYING.txt %{buildroot}/usr/share/package-licenses/qemu-guest-additions/b91b6ebd4f4725457f64e1d35e5a94c2bd35bcec || :
cp %{_builddir}/qemu-%{version}/subprojects/keycodemapdb/LICENSE.BSD %{buildroot}/usr/share/package-licenses/qemu-guest-additions/ea5b412c09f3b29ba1d81a61b878c5c16ffe69d8 || :
cp %{_builddir}/qemu-%{version}/subprojects/keycodemapdb/LICENSE.GPL2 %{buildroot}/usr/share/package-licenses/qemu-guest-additions/06877624ea5c77efe3b7e39b0f909eda6e25a4ec || :
cp %{_builddir}/qemu-%{version}/subprojects/libvfio-user/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/36fb901125ffda91bbec1cab3efc5c9f8f2d15a7 || :
cp %{_builddir}/qemu-%{version}/tests/lcitool/libvirt-ci/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/qemu-%{version}/tests/uefi-test-tools/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/234e74aeab28f7faad2baccf1a3f943b36ab895e || :
export GOAMD64=v2
GOAMD64=v2
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/qemu-guest-agent.service
## Remove excluded files
rm -f %{buildroot}*/usr/bin/elf2dmp
rm -f %{buildroot}*/usr/bin/ivshmem-client
rm -f %{buildroot}*/usr/bin/ivshmem-server
rm -f %{buildroot}*/usr/bin/qemu-edid
rm -f %{buildroot}*/usr/bin/qemu-i386
rm -f %{buildroot}*/usr/bin/qemu-img
rm -f %{buildroot}*/usr/bin/qemu-io
rm -f %{buildroot}*/usr/bin/qemu-keymap
rm -f %{buildroot}*/usr/bin/qemu-nbd
rm -f %{buildroot}*/usr/bin/qemu-pr-helper
rm -f %{buildroot}*/usr/bin/qemu-storage-daemon
rm -f %{buildroot}*/usr/bin/qemu-system-i386
rm -f %{buildroot}*/usr/bin/qemu-system-x86_64
rm -f %{buildroot}*/usr/bin/qemu-x86_64
rm -f %{buildroot}*/usr/bin/virtfs-proxy-helper
rm -f %{buildroot}*/usr/include/qemu-plugin.h
rm -f %{buildroot}*/usr/libexec/qemu-bridge-helper
rm -f %{buildroot}*/usr/libexec/qemu-pr-helper
rm -f %{buildroot}*/usr/libexec/vhost-user-gpu
rm -f %{buildroot}*/usr/libexec/virtfs-proxy-helper
rm -f %{buildroot}*/usr/libexec/virtiofsd
rm -f %{buildroot}*/usr/share/applications/qemu.desktop
rm -f %{buildroot}*/usr/share/man/man1/qemu-img.1
rm -f %{buildroot}*/usr/share/man/man1/qemu-storage-daemon.1
rm -f %{buildroot}*/usr/share/man/man7/qemu-storage-daemon-qmp-ref.7
rm -f %{buildroot}*/usr/share/man/man1/qemu.1
rm -f %{buildroot}*/usr/share/man/man1/virtfs-proxy-helper.1
rm -f %{buildroot}*/usr/share/man/man1/virtiofsd.1
rm -f %{buildroot}*/usr/share/man/man7/qemu-block-drivers.7
rm -f %{buildroot}*/usr/share/man/man7/qemu-cpu-models.7
rm -f %{buildroot}*/usr/share/man/man7/qemu-qmp-ref.7
rm -f %{buildroot}*/usr/share/man/man8/qemu-nbd.8
rm -f %{buildroot}*/usr/share/man/man8/qemu-pr-helper.8
rm -f %{buildroot}*/usr/include/fdt.h
rm -f %{buildroot}*/usr/include/libfdt.h
rm -f %{buildroot}*/usr/include/libfdt_env.h
rm -f %{buildroot}*/usr/lib64/pkgconfig/libfdt.pc
rm -f %{buildroot}*/usr/bin/qemu-vmsr-helper
## install_append content
rm -rvf %{buildroot}/usr/share/doc
rm -rvf %{buildroot}/usr/share/icons
rm -rvf %{buildroot}/usr/share/locale
rm -rvf %{buildroot}/usr/share/qemu
mkdir -pv %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
ln -sv ../qemu-guest-agent.service %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/qemu-guest-agent.service
## install_append end

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/qemu-guest-agent.service

%files bin
%defattr(-,root,root,-)
/usr/bin/qemu-ga

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qemu-guest-additions/01a6b4bf79aca9b556822601186afab86e8c4fbf
/usr/share/package-licenses/qemu-guest-additions/06877624ea5c77efe3b7e39b0f909eda6e25a4ec
/usr/share/package-licenses/qemu-guest-additions/0a0d7ae8e993794ae9c9ac5219c3d2bbf289471f
/usr/share/package-licenses/qemu-guest-additions/11bb99995c221415712bb5a6d6c0898f02936feb
/usr/share/package-licenses/qemu-guest-additions/1b5c06f43bf6e2039065b681398f6b99a4d552f8
/usr/share/package-licenses/qemu-guest-additions/234e74aeab28f7faad2baccf1a3f943b36ab895e
/usr/share/package-licenses/qemu-guest-additions/2807f3f1c4cb33b214defc4c7ab72f7e4e70a305
/usr/share/package-licenses/qemu-guest-additions/2b8b815229aa8a61e483fb4ba0588b8b6c491890
/usr/share/package-licenses/qemu-guest-additions/2b9d60c2972b476384af9900276837ac81954e80
/usr/share/package-licenses/qemu-guest-additions/2f02ed32418afe8cc25f30f269c63085bafe44f7
/usr/share/package-licenses/qemu-guest-additions/30a6e0a424471d8ac874b5616dd5a18c45fd6046
/usr/share/package-licenses/qemu-guest-additions/36fb901125ffda91bbec1cab3efc5c9f8f2d15a7
/usr/share/package-licenses/qemu-guest-additions/3e8117303a7ac9ce341dc761b8a4f5ac3696e0a3
/usr/share/package-licenses/qemu-guest-additions/3f226d574cd9547c3e4d934bb1ac4be3601a9782
/usr/share/package-licenses/qemu-guest-additions/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/qemu-guest-additions/4d6c5af1a9cc4eaab3b93353fc166d8e29c150c6
/usr/share/package-licenses/qemu-guest-additions/6b5c7cbcd561ea8f6bba9dd24393f995c1a006e9
/usr/share/package-licenses/qemu-guest-additions/7475b0da13789cd598fe0703f5337d37dd8b0b95
/usr/share/package-licenses/qemu-guest-additions/7fc5c71d1c403b07043376504d62f2ac73a75313
/usr/share/package-licenses/qemu-guest-additions/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/qemu-guest-additions/864f15fbb4dcd073bbe20eb3c0b839a45b8902ab
/usr/share/package-licenses/qemu-guest-additions/8b35225cbdbd6858fb081817cc9dbfe4bef26f5b
/usr/share/package-licenses/qemu-guest-additions/b91b6ebd4f4725457f64e1d35e5a94c2bd35bcec
/usr/share/package-licenses/qemu-guest-additions/c045813a6c514f2d30d60a07c6aaf3603850e608
/usr/share/package-licenses/qemu-guest-additions/c4cd5ba6f665cf9ecb44e0620c2c76140566cfc6
/usr/share/package-licenses/qemu-guest-additions/c5c8a68f4b80929b3e66f054f37bb9e16078847f
/usr/share/package-licenses/qemu-guest-additions/c690b05ff6431c277b59784e95169e0e0528a983
/usr/share/package-licenses/qemu-guest-additions/c9c057d4dc70e7a834d80b762663ca01a852ed13
/usr/share/package-licenses/qemu-guest-additions/ca46b2cea92edc93654b11c06c0073ec1a2e50e8
/usr/share/package-licenses/qemu-guest-additions/cedc99c80ddc135681756e652d55c72d89ebdfe7
/usr/share/package-licenses/qemu-guest-additions/e1f0ad62e4850a19b1f56b821f37fccbf84ec191
/usr/share/package-licenses/qemu-guest-additions/e7d563f52bf5295e6dba1d67ac23e9f6a160fab9
/usr/share/package-licenses/qemu-guest-additions/e9b568889ca9075b505c509f7a877a723cc9a4b0
/usr/share/package-licenses/qemu-guest-additions/ea5b412c09f3b29ba1d81a61b878c5c16ffe69d8
/usr/share/package-licenses/qemu-guest-additions/f12894289cb0f379f24b8d63e2e761dbcba1b216
/usr/share/package-licenses/qemu-guest-additions/f1a6a8f321d20cb5fbec859a848bff49ad31de69

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man7/qemu-ga-ref.7
/usr/share/man/man8/qemu-ga.8

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/qemu-guest-agent.service
/usr/lib/systemd/system/qemu-guest-agent.service
