#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x3353C9CEF108B584 (mdroth@utexas.edu)
#
Name     : qemu-guest-additions
Version  : 3.1.0
Release  : 107
URL      : http://wiki.qemu-project.org/download/qemu-3.1.0.tar.xz
Source0  : http://wiki.qemu-project.org/download/qemu-3.1.0.tar.xz
Source1  : qemu-guest-agent.service
Source99 : http://wiki.qemu-project.org/download/qemu-3.1.0.tar.xz.sig
Summary  : A lightweight multi-platform, multi-architecture disassembly framework
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSD-3-Clause CC0-1.0 GPL-2.0 GPL-3.0 LGPL-2.1 LGPL-3.0 MIT NCSA
Requires: qemu-guest-additions-autostart = %{version}-%{release}
Requires: qemu-guest-additions-bin = %{version}-%{release}
Requires: qemu-guest-additions-data = %{version}-%{release}
Requires: qemu-guest-additions-libexec = %{version}-%{release}
Requires: qemu-guest-additions-license = %{version}-%{release}
Requires: qemu-guest-additions-services = %{version}-%{release}
BuildRequires : attr-dev
BuildRequires : automake-dev
BuildRequires : bison
BuildRequires : buildreq-cmake
BuildRequires : buildreq-distutils3
BuildRequires : buildreq-qmake
BuildRequires : ceph-dev
BuildRequires : flex
BuildRequires : glib-dev
BuildRequires : gtk3-dev
BuildRequires : libaio-dev
BuildRequires : libcap-dev
BuildRequires : libcap-ng-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libseccomp-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : numactl-dev
BuildRequires : snappy-dev
BuildRequires : spice
BuildRequires : spice-dev
BuildRequires : spice-protocol
BuildRequires : usbredir-dev
BuildRequires : util-linux-dev
BuildRequires : zlib-dev
Patch1: configure.patch
Patch2: cores-default.patch
Patch3: 0001-Use-run-lock.patch
Patch4: CVE-2018-16872.patch
Patch5: CVE-2018-20191.patch
Patch6: CVE-2018-20124.patch
Patch7: CVE-2018-20123.patch
Patch8: CVE-2019-6778.patch
Patch9: CVE-2017-18043.nopatch
Patch10: CVE-2019-3812.patch

%description
Capstone is a disassembly framework with the target of becoming the ultimate
disasm engine for binary analysis and reversing in the security community.

%package autostart
Summary: autostart components for the qemu-guest-additions package.
Group: Default

%description autostart
autostart components for the qemu-guest-additions package.


%package bin
Summary: bin components for the qemu-guest-additions package.
Group: Binaries
Requires: qemu-guest-additions-data = %{version}-%{release}
Requires: qemu-guest-additions-libexec = %{version}-%{release}
Requires: qemu-guest-additions-license = %{version}-%{release}
Requires: qemu-guest-additions-services = %{version}-%{release}

%description bin
bin components for the qemu-guest-additions package.


%package data
Summary: data components for the qemu-guest-additions package.
Group: Data

%description data
data components for the qemu-guest-additions package.


%package libexec
Summary: libexec components for the qemu-guest-additions package.
Group: Default
Requires: qemu-guest-additions-license = %{version}-%{release}

%description libexec
libexec components for the qemu-guest-additions package.


%package license
Summary: license components for the qemu-guest-additions package.
Group: Default

%description license
license components for the qemu-guest-additions package.


%package services
Summary: services components for the qemu-guest-additions package.
Group: Systemd services

%description services
services components for the qemu-guest-additions package.


%prep
%setup -q -n qemu-3.1.0
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
%patch8 -p1
%patch10 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1553719297
export LDFLAGS="${LDFLAGS} -fno-lto"
export CFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static --disable-sdl \
--enable-vnc \
--enable-gtk \
--enable-kvm \
--disable-strip \
--target-list='i386-softmmu x86_64-softmmu i386-linux-user x86_64-linux-user' \
--enable-spice \
--enable-rbd \
--extra-cflags="-O3" \
--enable-attr \
--enable-cap-ng \
--enable-virtfs \
--enable-vhost-net \
--enable-usb-redir \
--python=/usr/bin/python \
--enable-seccomp \
--enable-linux-aio
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check || :

%install
export SOURCE_DATE_EPOCH=1553719297
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qemu-guest-additions
cp COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/COPYING
cp COPYING.LIB %{buildroot}/usr/share/package-licenses/qemu-guest-additions/COPYING.LIB
cp LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/LICENSE
cp capstone/LICENSE.TXT %{buildroot}/usr/share/package-licenses/qemu-guest-additions/capstone_LICENSE.TXT
cp capstone/LICENSE_LLVM.TXT %{buildroot}/usr/share/package-licenses/qemu-guest-additions/capstone_LICENSE_LLVM.TXT
cp capstone/bindings/python/LICENSE.TXT %{buildroot}/usr/share/package-licenses/qemu-guest-additions/capstone_bindings_python_LICENSE.TXT
cp disas/libvixl/LICENCE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/disas_libvixl_LICENCE
cp dtc/README.license %{buildroot}/usr/share/package-licenses/qemu-guest-additions/dtc_README.license
cp linux-headers/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/linux-headers_COPYING
cp roms/QemuMacDrivers/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_QemuMacDrivers_COPYING
cp roms/SLOF/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_SLOF_LICENSE
cp roms/ipxe/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_ipxe_COPYING
cp roms/ipxe/COPYING.GPLv2 %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_ipxe_COPYING.GPLv2
cp roms/ipxe/src/include/ipxe/efi/LICENCE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_ipxe_src_include_ipxe_efi_LICENCE
cp roms/openbios/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_openbios_COPYING
cp roms/openbios/Documentation/kernel/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_openbios_Documentation_kernel_COPYING
cp roms/openbios/utils/devbios/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_openbios_utils_devbios_COPYING
cp roms/openhackware/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_openhackware_COPYING
cp roms/qemu-palcode/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_qemu-palcode_COPYING
cp roms/seabios-hppa/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_seabios-hppa_COPYING
cp roms/seabios-hppa/COPYING.LESSER %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_seabios-hppa_COPYING.LESSER
cp roms/seabios/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_seabios_COPYING
cp roms/seabios/COPYING.LESSER %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_seabios_COPYING.LESSER
cp roms/sgabios/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_sgabios_COPYING
cp roms/skiboot/LICENCE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_skiboot_LICENCE
cp roms/skiboot/ccan/array_size/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_skiboot_ccan_array_size_LICENSE
cp roms/skiboot/ccan/build_assert/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_skiboot_ccan_build_assert_LICENSE
cp roms/skiboot/ccan/check_type/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_skiboot_ccan_check_type_LICENSE
cp roms/skiboot/ccan/container_of/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_skiboot_ccan_container_of_LICENSE
cp roms/skiboot/ccan/endian/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_skiboot_ccan_endian_LICENSE
cp roms/skiboot/ccan/list/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_skiboot_ccan_list_LICENSE
cp roms/skiboot/ccan/short_types/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_skiboot_ccan_short_types_LICENSE
cp roms/skiboot/ccan/str/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_skiboot_ccan_str_LICENSE
cp roms/u-boot-sam460ex/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_u-boot-sam460ex_COPYING
cp roms/u-boot-sam460ex/board/ACube/bios_emulator/scitech/src/x86emu/LICENSE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_u-boot-sam460ex_board_ACube_bios_emulator_scitech_src_x86emu_LICENSE
cp roms/u-boot-sam460ex/fs/jffs2/LICENCE %{buildroot}/usr/share/package-licenses/qemu-guest-additions/roms_u-boot-sam460ex_fs_jffs2_LICENCE
cp slirp/COPYRIGHT %{buildroot}/usr/share/package-licenses/qemu-guest-additions/slirp_COPYRIGHT
cp tests/fp/berkeley-softfloat-3/COPYING.txt %{buildroot}/usr/share/package-licenses/qemu-guest-additions/tests_fp_berkeley-softfloat-3_COPYING.txt
cp tests/fp/berkeley-testfloat-3/COPYING.txt %{buildroot}/usr/share/package-licenses/qemu-guest-additions/tests_fp_berkeley-testfloat-3_COPYING.txt
cp tests/qemu-iotests/COPYING %{buildroot}/usr/share/package-licenses/qemu-guest-additions/tests_qemu-iotests_COPYING
cp ui/keycodemapdb/LICENSE.BSD %{buildroot}/usr/share/package-licenses/qemu-guest-additions/ui_keycodemapdb_LICENSE.BSD
cp ui/keycodemapdb/LICENSE.GPL2 %{buildroot}/usr/share/package-licenses/qemu-guest-additions/ui_keycodemapdb_LICENSE.GPL2
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/qemu-guest-agent.service
## install_append content
rm -rf %{buildroot}/usr/share/locale
mkdir -p %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
ln -s ../qemu-guest-agent.service  %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/qemu-guest-agent.service
## install_append end

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/qemu-guest-agent.service

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/ivshmem-client
%exclude /usr/bin/ivshmem-server
%exclude /usr/bin/qemu-edid
%exclude /usr/bin/qemu-i386
%exclude /usr/bin/qemu-img
%exclude /usr/bin/qemu-io
%exclude /usr/bin/qemu-keymap
%exclude /usr/bin/qemu-nbd
%exclude /usr/bin/qemu-pr-helper
%exclude /usr/bin/qemu-system-i386
%exclude /usr/bin/qemu-system-x86_64
%exclude /usr/bin/qemu-x86_64
%exclude /usr/bin/virtfs-proxy-helper
/usr/bin/qemu-ga

%files data
%defattr(-,root,root,-)
%exclude /usr/share/qemu/QEMU,cgthree.bin
%exclude /usr/share/qemu/QEMU,tcx.bin
%exclude /usr/share/qemu/bamboo.dtb
%exclude /usr/share/qemu/bios-256k.bin
%exclude /usr/share/qemu/bios.bin
%exclude /usr/share/qemu/canyonlands.dtb
%exclude /usr/share/qemu/efi-e1000.rom
%exclude /usr/share/qemu/efi-e1000e.rom
%exclude /usr/share/qemu/efi-eepro100.rom
%exclude /usr/share/qemu/efi-ne2k_pci.rom
%exclude /usr/share/qemu/efi-pcnet.rom
%exclude /usr/share/qemu/efi-rtl8139.rom
%exclude /usr/share/qemu/efi-virtio.rom
%exclude /usr/share/qemu/efi-vmxnet3.rom
%exclude /usr/share/qemu/hppa-firmware.img
%exclude /usr/share/qemu/keymaps/ar
%exclude /usr/share/qemu/keymaps/bepo
%exclude /usr/share/qemu/keymaps/common
%exclude /usr/share/qemu/keymaps/cz
%exclude /usr/share/qemu/keymaps/da
%exclude /usr/share/qemu/keymaps/de
%exclude /usr/share/qemu/keymaps/de-ch
%exclude /usr/share/qemu/keymaps/en-gb
%exclude /usr/share/qemu/keymaps/en-us
%exclude /usr/share/qemu/keymaps/es
%exclude /usr/share/qemu/keymaps/et
%exclude /usr/share/qemu/keymaps/fi
%exclude /usr/share/qemu/keymaps/fo
%exclude /usr/share/qemu/keymaps/fr
%exclude /usr/share/qemu/keymaps/fr-be
%exclude /usr/share/qemu/keymaps/fr-ca
%exclude /usr/share/qemu/keymaps/fr-ch
%exclude /usr/share/qemu/keymaps/hr
%exclude /usr/share/qemu/keymaps/hu
%exclude /usr/share/qemu/keymaps/is
%exclude /usr/share/qemu/keymaps/it
%exclude /usr/share/qemu/keymaps/ja
%exclude /usr/share/qemu/keymaps/lt
%exclude /usr/share/qemu/keymaps/lv
%exclude /usr/share/qemu/keymaps/mk
%exclude /usr/share/qemu/keymaps/modifiers
%exclude /usr/share/qemu/keymaps/nl
%exclude /usr/share/qemu/keymaps/nl-be
%exclude /usr/share/qemu/keymaps/no
%exclude /usr/share/qemu/keymaps/pl
%exclude /usr/share/qemu/keymaps/pt
%exclude /usr/share/qemu/keymaps/pt-br
%exclude /usr/share/qemu/keymaps/ru
%exclude /usr/share/qemu/keymaps/sl
%exclude /usr/share/qemu/keymaps/sv
%exclude /usr/share/qemu/keymaps/th
%exclude /usr/share/qemu/keymaps/tr
%exclude /usr/share/qemu/kvmvapic.bin
%exclude /usr/share/qemu/linuxboot.bin
%exclude /usr/share/qemu/linuxboot_dma.bin
%exclude /usr/share/qemu/multiboot.bin
%exclude /usr/share/qemu/openbios-ppc
%exclude /usr/share/qemu/openbios-sparc32
%exclude /usr/share/qemu/openbios-sparc64
%exclude /usr/share/qemu/palcode-clipper
%exclude /usr/share/qemu/petalogix-ml605.dtb
%exclude /usr/share/qemu/petalogix-s3adsp1800.dtb
%exclude /usr/share/qemu/ppc_rom.bin
%exclude /usr/share/qemu/pxe-e1000.rom
%exclude /usr/share/qemu/pxe-eepro100.rom
%exclude /usr/share/qemu/pxe-ne2k_pci.rom
%exclude /usr/share/qemu/pxe-pcnet.rom
%exclude /usr/share/qemu/pxe-rtl8139.rom
%exclude /usr/share/qemu/pxe-virtio.rom
%exclude /usr/share/qemu/qemu-icon.bmp
%exclude /usr/share/qemu/qemu_logo_no_text.svg
%exclude /usr/share/qemu/qemu_vga.ndrv
%exclude /usr/share/qemu/s390-ccw.img
%exclude /usr/share/qemu/s390-netboot.img
%exclude /usr/share/qemu/sgabios.bin
%exclude /usr/share/qemu/skiboot.lid
%exclude /usr/share/qemu/slof.bin
%exclude /usr/share/qemu/spapr-rtas.bin
%exclude /usr/share/qemu/trace-events-all
%exclude /usr/share/qemu/u-boot-sam460-20100605.bin
%exclude /usr/share/qemu/u-boot.e500
%exclude /usr/share/qemu/vgabios-bochs-display.bin
%exclude /usr/share/qemu/vgabios-cirrus.bin
%exclude /usr/share/qemu/vgabios-qxl.bin
%exclude /usr/share/qemu/vgabios-ramfb.bin
%exclude /usr/share/qemu/vgabios-stdvga.bin
%exclude /usr/share/qemu/vgabios-virtio.bin
%exclude /usr/share/qemu/vgabios-vmware.bin
%exclude /usr/share/qemu/vgabios.bin

%files libexec
%defattr(-,root,root,-)
%exclude /usr/libexec/qemu-bridge-helper

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qemu-guest-additions/COPYING
/usr/share/package-licenses/qemu-guest-additions/COPYING.LIB
/usr/share/package-licenses/qemu-guest-additions/LICENSE
/usr/share/package-licenses/qemu-guest-additions/capstone_LICENSE.TXT
/usr/share/package-licenses/qemu-guest-additions/capstone_LICENSE_LLVM.TXT
/usr/share/package-licenses/qemu-guest-additions/capstone_bindings_python_LICENSE.TXT
/usr/share/package-licenses/qemu-guest-additions/disas_libvixl_LICENCE
/usr/share/package-licenses/qemu-guest-additions/dtc_README.license
/usr/share/package-licenses/qemu-guest-additions/linux-headers_COPYING
/usr/share/package-licenses/qemu-guest-additions/roms_QemuMacDrivers_COPYING
/usr/share/package-licenses/qemu-guest-additions/roms_SLOF_LICENSE
/usr/share/package-licenses/qemu-guest-additions/roms_ipxe_COPYING
/usr/share/package-licenses/qemu-guest-additions/roms_ipxe_COPYING.GPLv2
/usr/share/package-licenses/qemu-guest-additions/roms_ipxe_src_include_ipxe_efi_LICENCE
/usr/share/package-licenses/qemu-guest-additions/roms_openbios_COPYING
/usr/share/package-licenses/qemu-guest-additions/roms_openbios_Documentation_kernel_COPYING
/usr/share/package-licenses/qemu-guest-additions/roms_openbios_utils_devbios_COPYING
/usr/share/package-licenses/qemu-guest-additions/roms_openhackware_COPYING
/usr/share/package-licenses/qemu-guest-additions/roms_qemu-palcode_COPYING
/usr/share/package-licenses/qemu-guest-additions/roms_seabios-hppa_COPYING
/usr/share/package-licenses/qemu-guest-additions/roms_seabios-hppa_COPYING.LESSER
/usr/share/package-licenses/qemu-guest-additions/roms_seabios_COPYING
/usr/share/package-licenses/qemu-guest-additions/roms_seabios_COPYING.LESSER
/usr/share/package-licenses/qemu-guest-additions/roms_sgabios_COPYING
/usr/share/package-licenses/qemu-guest-additions/roms_skiboot_LICENCE
/usr/share/package-licenses/qemu-guest-additions/roms_skiboot_ccan_array_size_LICENSE
/usr/share/package-licenses/qemu-guest-additions/roms_skiboot_ccan_build_assert_LICENSE
/usr/share/package-licenses/qemu-guest-additions/roms_skiboot_ccan_check_type_LICENSE
/usr/share/package-licenses/qemu-guest-additions/roms_skiboot_ccan_container_of_LICENSE
/usr/share/package-licenses/qemu-guest-additions/roms_skiboot_ccan_endian_LICENSE
/usr/share/package-licenses/qemu-guest-additions/roms_skiboot_ccan_list_LICENSE
/usr/share/package-licenses/qemu-guest-additions/roms_skiboot_ccan_short_types_LICENSE
/usr/share/package-licenses/qemu-guest-additions/roms_skiboot_ccan_str_LICENSE
/usr/share/package-licenses/qemu-guest-additions/roms_u-boot-sam460ex_COPYING
/usr/share/package-licenses/qemu-guest-additions/roms_u-boot-sam460ex_board_ACube_bios_emulator_scitech_src_x86emu_LICENSE
/usr/share/package-licenses/qemu-guest-additions/roms_u-boot-sam460ex_fs_jffs2_LICENCE
/usr/share/package-licenses/qemu-guest-additions/slirp_COPYRIGHT
/usr/share/package-licenses/qemu-guest-additions/tests_fp_berkeley-softfloat-3_COPYING.txt
/usr/share/package-licenses/qemu-guest-additions/tests_fp_berkeley-testfloat-3_COPYING.txt
/usr/share/package-licenses/qemu-guest-additions/tests_qemu-iotests_COPYING
/usr/share/package-licenses/qemu-guest-additions/ui_keycodemapdb_LICENSE.BSD
/usr/share/package-licenses/qemu-guest-additions/ui_keycodemapdb_LICENSE.GPL2

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/qemu-guest-agent.service
/usr/lib/systemd/system/qemu-guest-agent.service
